-- MySQL Script generated by MySQL Workbench
-- sam. 31 oct. 2015 20:54:17 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WaTuGa_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WaTuGa_DB` ;

-- -----------------------------------------------------
-- Schema WaTuGa_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WaTuGa_DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `WaTuGa_DB` ;

-- -----------------------------------------------------
-- Table `WaTuGa_DB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaTuGa_DB`.`User` ;

CREATE TABLE IF NOT EXISTS `WaTuGa_DB`.`User` (
  `pseudo` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pseudo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WaTuGa_DB`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaTuGa_DB`.`Review` ;

CREATE TABLE IF NOT EXISTS `WaTuGa_DB`.`Review` (
  `id` INT NOT NULL,
  `creationDate` TIMESTAMP NOT NULL DEFAULT 0,
  `editionDate` TIMESTAMP NOT NULL DEFAULT 0,
  `title` VARCHAR(45) NOT NULL,
  `release` TIMESTAMP DEFAULT 0,
  `producer` VARCHAR(45) NULL,
  `summary` VARCHAR(45) NULL,
  `kind` VARCHAR(45) NULL,
  `nationnality` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WaTuGa_DB`.`Actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaTuGa_DB`.`Actor` ;

CREATE TABLE IF NOT EXISTS `WaTuGa_DB`.`Actor` (
  `review_id` INT NOT NULL,
  `lastename` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`review_id`, `lastename`, `firstname`),
  CONSTRAINT `Actor_review_id_fk`
    FOREIGN KEY (`review_id`)
    REFERENCES `WaTuGa_DB`.`Review` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WaTuGa_DB`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaTuGa_DB`.`Comment` ;

CREATE TABLE IF NOT EXISTS `WaTuGa_DB`.`Comment` (
  `review_id` INT NOT NULL,
  `comment` VARCHAR(45) NOT NULL,
  `user_pseudo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`review_id`, `user_pseudo`),
  INDEX `user_pseudo_idx` (`user_pseudo` ASC),
  CONSTRAINT `Comment_review_id_fk`
    FOREIGN KEY (`review_id`)
    REFERENCES `WaTuGa_DB`.`Review` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Comment_user_pseudo_fk`
    FOREIGN KEY (`user_pseudo`)
    REFERENCES `WaTuGa_DB`.`User` (`pseudo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WaTuGa_DB`.`Mark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WaTuGa_DB`.`Mark` ;

CREATE TABLE IF NOT EXISTS `WaTuGa_DB`.`Mark` (
  `review_id` INT NOT NULL,
  `mark` VARCHAR(45) NULL,
  `user_pseudo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`review_id`, `user_pseudo`),
  INDEX `user_pseudo_idx` (`user_pseudo` ASC),
  CONSTRAINT `Mark_review_id_fk`
    FOREIGN KEY (`review_id`)
    REFERENCES `WaTuGa_DB`.`Review` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Mark_user_pseudo-fk`
    FOREIGN KEY (`user_pseudo`)
    REFERENCES `WaTuGa_DB`.`User` (`pseudo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
