-- MySQL Script generated by MySQL Workbench
-- jeu. 29 oct. 2015 04:11:18 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `pseudo` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pseudo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Movie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Movie` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `release` TIMESTAMP NOT NULL,
  `producer` VARCHAR(45) NULL,
  `summary` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Actor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Actor` (
  `id` INT NOT NULL,
  `lastename` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kind`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kind` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kind` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nationnality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nationnality` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nationnality` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Review` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Review` (
  `id` INT NOT NULL,
  `creationDate` TIMESTAMP NOT NULL,
  `editionDate` TIMESTAMP NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `movie_id_idx` (`movie_id` ASC),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`Movie` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `review_id` INT NOT NULL,
  `comment` VARCHAR(45) NOT NULL,
  `user_pseudo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`review_id`, `user_pseudo`),
  INDEX `user_pseudo_idx` (`user_pseudo` ASC),
  CONSTRAINT `review_id`
    FOREIGN KEY (`review_id`)
    REFERENCES `mydb`.`Review` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_pseudo`
    FOREIGN KEY (`user_pseudo`)
    REFERENCES `mydb`.`User` (`pseudo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mark` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mark` (
  `review_id` INT NOT NULL,
  `mark` VARCHAR(45) NULL,
  `user_pseudo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`review_id`, `user_pseudo`),
  INDEX `user_pseudo_idx` (`user_pseudo` ASC),
  CONSTRAINT `review_id`
    FOREIGN KEY (`review_id`)
    REFERENCES `mydb`.`Review` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_pseudo`
    FOREIGN KEY (`user_pseudo`)
    REFERENCES `mydb`.`User` (`pseudo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovieKind`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MovieKind` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MovieKind` (
  `movie_id` INT NOT NULL,
  `kind_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `kind_id`),
  INDEX `kind_id_idx` (`kind_id` ASC),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`Movie` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `kind_id`
    FOREIGN KEY (`kind_id`)
    REFERENCES `mydb`.`Kind` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovieNationnality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MovieNationnality` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MovieNationnality` (
  `movie_id` INT NOT NULL,
  `nationnality_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `nationnality_id`),
  INDEX `nationnality_id_idx` (`nationnality_id` ASC),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`Movie` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `nationnality_id`
    FOREIGN KEY (`nationnality_id`)
    REFERENCES `mydb`.`Nationnality` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovieActor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MovieActor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MovieActor` (
  `movie_id` INT NOT NULL,
  `actor_id` INT NULL,
  PRIMARY KEY (`movie_id`),
  INDEX `actor_id_idx` (`movie_id` ASC, `actor_id` ASC),
  CONSTRAINT `movie_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Movie` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `actor_id`
    FOREIGN KEY (`movie_id` , `actor_id`)
    REFERENCES `mydb`.`Actor` (`id` , `id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
